server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8061/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: person-db-service
        uri: lb://person-db-service
        predicates:
        - Path=/persons/**
        filters:
        - RewritePath=/persons/(?<path>.*), /$\{path}
      - id: person-service
        uri: lb://person-service
        predicates:
        - Path=/person-service/**
        filters:
        - RewritePath=/person-service/(?<path>.*), /$\{path}