server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8061/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring.datasource:
  url: jdbc:mysql://localhost:3306/javapub?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  username: admin
  password: admin
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false